export { Home } from './home/Home';
export { Cart } from './cart/Cart';
export { Checkout } from './checkout/Checkout';
export { Products } from './products/Products';
export { SignIn } from './signIn/SignIn';
export { SignUp } from './singUp/SignUp';
export { Product } from './single-product/Product';
export { PageNotFound } from './404-page/PageNotFound';
export { PrivacyPolicy } from './privacy-policy/PrivacyPolicy';
